class Item {
    constructor(image, name, price, isFavorite, description) {
      this.image = image;
      this.name = name;
      this.price = price;
      this.isFavorite = isFavorite;
      this.description = description;
    }
}

var app = angular.module("app", []);

KouignAmann = new Item("https://lh3.googleusercontent.com/4-if2dwav6dandec3J8y3SNpCGsSg78sZqR-udURvoKTL1aYO_F4kfX1T1c_4kIDGn8=w2400",  "Kouign Amann", "2.99 € / vnt.", false, "Šis tradicinis prancūziškas kepinys pagamintas iš trapios, sviestinės tešlos, kruopščiai sulankstytos ir iškeptos iki tobulumo. To rezultatas – karamelizuotas, traškus išorinis sluoksnis su švelniu vidumi. Kiekvienas kąsnis – skonio ir tekstūros harmonijos sprogimas. Mūsų Kouign Amann yra skirtas tiems, kurie ieško unikalaus ir skanaus desertų, išsiskiriančių iš kitų. Nesvarbu, ar tai yra ypatinga proga, ar tiesiog noras palepinti savo skonio receptorius, mūsų Kouign Amann tikrai paliks neišdildomą įspūdį! ");
Profiterole = new Item("https://lh5.googleusercontent.com/kX9JmxywKqfUErwZ10rjvy3T37eIXQSlwhFDEPwsO-KwPW3TMK_8fapl8yWYCz6PgaA=w2400",  "Profiterole", "1.99 € / vnt.", true, "Šis populiarus prancūziškas desertas pagamintas iš lengvos ir korėtos tešlos, įdarytas gardžiu kremu ir dekoruotas delikačiais pabarstukais, o ant viršaus užpiltas kokybiškas šokoladas suteikia malonumą kiekviename kąsnyje. Šie skanūs ir elegantiški kepinukai tikrai sužavės jus ir jūsų svečius. Nesvarbu, ar rengiatės ypatingam vakarienės vakarui, ar tiesiog ieškote skanaus užkandžio, mūsų Profiterole tinka bet kokiam renginiui. Apsilankykite mūsų kepyklėlėje ir atraskite naujas skonio subtilybes - jūs tikrai nepasigailėsite!");
Macarons = new Item("https://lh6.googleusercontent.com/vye5XF4AFPWqthCaBpyvr9lKhUoqbE2QZW_RXuwrd_ftcuP0NirMWQoA0irkm_1-Y6k=w2400",  "Macarons", "1.59 € / vnt.", true, "Nors pavadinimas ir primena makaronus, tarp šių sausainių ir makaronų bendro yra tik jų kilmės šalis. Šie dailūs sausainiai pradėti kepti Italijoje, tačiau, pasiekę Prancūziją, užkariavo šios šalies konditerių širdis ir tapo vienu iš šalies simbolių. Mūsų kepykla šiuos sausainius gamina pagal klasikinį jų receptą, tokį, koks vyrauja ir pačiose žymiausiose Prancūzijos kepyklose. Todėl maloniai kviečiame paragauti tikrojo Prancūzijos skonio!");
Chouquettes = new Item("https://lh6.googleusercontent.com/RB1hPtx5ReCM8ikZpFVtRy9p7-XImY4La7_OsKsBfhkRhTqmiv343UQkHlUVsFZOaSU=w2400",  "Chouquettes", "8.99 € / kg.", false, "Didelio populiarumo sulaukęs Prancūzijos kepinys. Šie maži, plikytos tešlos sausainiai kepami iš traškios, sluoksniuotos tešlos, apibarstomi cukrumi ir patiekiami su švelniu grietinėlės kremu viduje. Jų subtilus skonis ir kreminė konsistencija žavi netgi labiausiai išrankius gurmanus. Nesvarbu, ar ieškote mažo skanėsto vakarienei, ar trokštate kažko saldaus ir lengvo, mūsų kepami Chouquettes visada yra tobulas pasirinkimas. Apsilankykite mūsų kepyklėlėje ir atraskite naują skonio pojūtį!");
Madeline = new Item("https://lh5.googleusercontent.com/WhWxT-AVjZfqSfsnNN7u0fhD0WKwhbth5HThsfPOHGYzsiJ3Hq0eRBuiut4nq7DV7zo=w2400",  "Madeline", "0.79 € / vnt.", false, "Šie malonūs kepinukai yra pagaminti iš subtilios, lengvos tešlos, kuriai būdingas puikus švelnumas ir lengvumas, ir apibarstyti saldžiais karamelės gabaliukais, suteikiančiais papildomą skonio gilumą. Tai puikus užkandis, skirtas visiems, kurie nori pasimėgauti subtiliu, bet įsimintinu desertu. Mūsų Madeleine puikiai tiks visiems, kurie ieško skanių užkandžių, ar tai būtų kasdienybė, ar ypatingas renginys. Apsilankykite mūsų kepyklėlėje ir atraskite naujas skonio subtilybes, kuriomis galėsite džiaugtis bet kuriuo metu!");
Religieuse = new Item("https://lh5.googleusercontent.com/4HDhmwsH2rRhsXAT4So0KTyjtueQ6zHVadaxH5ntEL5u7XwBDvDQr1cfq4B9KxTOsEo=w2400",  "Religieuse", "2.99 € / vnt.", false, "Šis puikus desertas gaminamas iš švelnios, kreminės tešlos, apipiltos švelniu kremu, pagamintu iš kokybiškiausių ingredientų. Šis minkštas ir švelnus desertas tikrai atitiks jūsų skonio poreikius. Nesvarbu, ar ieškote saldumo kasdieniam gyvenimui, ar norite sukurti įspūdingą desertų stalą, mūsų Religieuse tikrai atitiks jūsų lūkesčius. Apsilankykite mūsų kepyklėlėje ir patirkite šio nuostabaus deserto kūrybiškumą!");
PainAuChocolate = new Item("https://lh3.googleusercontent.com/Mp0Te2xwOF5_howmFs2uuJwyo7YgWMw8cArwH8ckWsJ1ZRbc1UkuP9PIxsosP08S0Jg=w2400",  "Pain au Chocolate", "1.39 € / vnt.", true, "Tai tobulas desertas bet kuriam paros metui. Šios bandelės pagamintos iš lengvų ir traškių tešlos sluoksnių, kurie užpildyti kokybišku šokoladu. Šio deserto kvapui ir tirpsmui burnoje neįmanoma atsispirti – tai tikra prancūziškų kepinių magija. Todėl kviečiame kiekvieną iš Jūsų palepinti save šia ypatinga, nepamirštama patirtimi kiekviename kąsnyje!");
Canneles = new Item("https://lh4.googleusercontent.com/R6UwDJ2oqTqtFeVvVaOwCyYRxcslk3pYpTtWwz8952QNEDrX-zipbK9tdCdB5f4mTyM=w2400",  "Canneles", "0.99 € / vnt.", true, "Vienas iš klasikinių Prancūzijos desertų, turinčių savyje kažką labai jaukaus, romantiško ir žinoma, saldaus... Tai vienas iš išskirtiniausių desertų Prancūzijoje, nes išsiskiria tiek savo forma, tiek tekstūra, tiek skoniu. Išorėje šie pyragėliai yra tamsios auksinės spalvos, paviršius tvirtas, traškus, o viduje – šviesūs, minkšti, drėgni, tekstūra kreminė. O kvapas nepriekaištingas ir nepamirštamas, nes šlakelis tamsaus kokybiško romo ir vanilės tiesiog kuria stebuklus. Tad kviečiame paragauti prancūziškos virtuvės stebuklų ir Jus!");
Croissant = new Item("https://lh5.googleusercontent.com/xl6jZP91GISAwSsHpxPzvAfVFkpekqq6YPTx3u-WPVNoaRre8Q5iVvGGduR1cbzxBgo=w2400",  "Croissant", "1.29 € / vnt.", true, "Šis tradicinis prancūziškas kepinys pagamintas iš trapios, sviestinės tešlos, kruopščiai sulankstytos ir iškeptos iki tobulumo. To rezultatas – karamelizuotas, traškus išorinis sluoksnis su švelniu vidumi. Kiekvienas kąsnis – skonio ir tekstūros harmonijos sprogimas. Mūsų Kouign Amann yra skirtas tiems, kurie ieško unikalaus ir skanaus desertų, išsiskiriančių iš kitų. Nesvarbu, ar tai yra ypatinga proga, ar tiesiog noras palepinti savo skonio receptorius, mūsų Kouign Amann tikrai paliks neišdildomą įspūdį!");

ItemsList = [
    KouignAmann, Profiterole, Macarons, Chouquettes, Madeline, Religieuse, PainAuChocolate, Canneles, Croissant
];

app.controller("controller", function($scope) {
  $scope.records = ItemsList;
});